name: Hello world
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Say hello
              run: echo "Hello, world!"

            - name: Show current directory
              run: pwd

            - name: List files
              run: ls -lrtah    