name: Timeout Example
on: [push]

jobs:
    timeout-job:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: start
              run: echo "Job "

            - name: Long Running Task
              run: |
                  echo "Starting a long task..."
                  sleep 120
                  echo "This will not be printed if the job times out."
